monolog:
    handlers:
        debug_log:
            type: rotating_file
            path: "%kernel.logs_dir%/debug/%kernel.environment%.log"
            level: debug
            max_files: 14
        error_log:
            type: rotating_file
            path: "%kernel.logs_dir%/error/%kernel.environment%.log"
            level: error
            max_files: 14
        info_log:
            type: rotating_file
            path: "%kernel.logs_dir%/info/%kernel.environment%.log"
            level: info
            max_files: 14
        console:
            type: console
            process_psr_3_messages: false
            channels: [ "!event", "!doctrine" ]
