# This is a local dev environment
# it will create your all-around needs
# by Dominic Poppe

# including NGINX & PHP as web server
# including a MariaDB docker
# including a REDIS docker
# including a PHPMYADMIN docker
# including a SFTP docker
# including an Axigen docker (send mails, receive mails, create users...)

# Webserver (PHP & NGINX)
#   http://localhost/ or http://127.0.0.1

# MariaDB
#   localhost:3306 -> DB (user: root | password: rootPassword | database: devDB)

# Redis
#   localhost:6379 (no password)

# PHPMYADMIN
#   http://localhost:9090

# SFTP
#   sftp://localhost:2222 | user: foo | pass: pass

# Axigen (when accessing the admin interface, you will create an account, for domain just do "localhost")
#   https://localhost:443 -> Webmail
#   https://localhost:9443 -> Admin Interface
#   localhost:25 <- smtp server, no tls
#   localhost:143 <- imap server, no tls

version: "3.1"

services:
  PROJECTNAME_db:
    container_name: PROJECTNAME_db
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: devDB
      TZ: Europe/Berlin
    ports:
      - 3306:3306
    volumes:
      - ./docker/db:/var/lib/mysql

  PROJECTNAME_php:
    container_name: PROJECTNAME_php
    build:
      context: .
      dockerfile: ./docker/php/php_dockerfile
      args:
        TIMEZONE: Europe/Berlin
    depends_on:
      - PROJECTNAME_db
    volumes:
      - ./:/var/www/

  PROJECTNAME_nginx:
    container_name: PROJECTNAME_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/nginx_dockerfile
    volumes:
      - ./:/var/www/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/nginx/logs:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - PROJECTNAME_php

  PROJECTNAME_redis:
    container_name: PROJECTNAME_redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  PROJECTNAME_phpmyadmin:
    container_name: PROJECTNAME_phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - PROJECTNAME_db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootPassword
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_USER: root
      MYSQL_PASSWORD: rootPassword
    ports:
      - 9090:80
    volumes:
      - ./docker/phpmyadmin:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

  PROJECTNAME_sftp:
    container_name: PROJECTNAME_sftp
    image: atmoz/sftp
    volumes:
      - ./docker/sftp:/home/foo/upload
    ports:
      - "2222:22"
    command: foo:pass:1001

  PROJECTNAME_axigen:
    container_name: PROJECTNAME_axigen
    image: axigen/axigen
    ports:
      - "443:443"
      - "9443:9443"
      - "993:993"
      - "995:995"
      - "25:25"
      - "465:465"
      - "9000:9000"
      - "7000:7000"
    volumes:
      - ./docker/axigen:/var/opt/axigen
